// Content script for Notion pages
console.log('Notion to Nanobanana Pro: Content script loaded');

// Listen for messages from background script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'showPromptModal') {
    handleGenerateImageFromContextMenu(request.selectedText);
  }
});

// Get the current block element based on selection
function getCurrentBlockElement() {
  const selection = window.getSelection();
  if (selection.rangeCount > 0) {
    const range = selection.getRangeAt(0);
    const container = range.commonAncestorContainer;
    const blockElement = container.nodeType === 3
      ? container.parentElement.closest('[data-block-id]')
      : container.closest('[data-block-id]');
    return blockElement;
  }
  return null;
}

// Handle image generation from context menu
async function handleGenerateImageFromContextMenu(selectedText) {
  if (!selectedText || !selectedText.trim()) {
    showNotification('テキストが選択されていません (No text selected)', 'error');
    return;
  }

  // Get current block element for insertion
  const blockElement = getCurrentBlockElement();

  // Show prompt selection modal
  const prompt = await showPromptModal(selectedText);

  if (!prompt) {
    // User cancelled
    return;
  }

  showNotification('画像を生成中... (Generating image...)', 'info');

  try {
    // Send message to background script to generate image
    const response = await chrome.runtime.sendMessage({
      action: 'generateImage',
      prompt: prompt
    });

    if (response.success && response.imageUrl) {
      // Insert image directly into Notion DOM
      insertImageIntoNotion(response.imageUrl, blockElement);
      showNotification('画像を生成しました！ (Image generated and added!)', 'success');
    } else {
      showNotification(`エラー: ${response.error}`, 'error');
    }
  } catch (error) {
    console.error('Error generating image:', error);
    showNotification(`エラー: ${error.message}`, 'error');
  }
}

// Insert image into Notion page by manipulating DOM
function insertImageIntoNotion(imageUrl, afterBlock) {
  try {
    // Create a new image block
    const imageBlock = document.createElement('div');
    imageBlock.className = 'notion-image-block';
    imageBlock.setAttribute('data-block-id', generateUUID());
    imageBlock.style.cssText = `
      width: 100%;
      max-width: 100%;
      margin: 4px 0;
      padding: 3px 2px;
    `;

    // Create image wrapper
    const imageWrapper = document.createElement('div');
    imageWrapper.style.cssText = `
      position: relative;
      width: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
    `;

    // Create image element
    const img = document.createElement('img');
    img.src = imageUrl;
    img.alt = 'Generated by Nanobanana Pro';
    img.style.cssText = `
      max-width: 100%;
      height: auto;
      border-radius: 3px;
      box-shadow: rgba(15, 15, 15, 0.1) 0px 0px 0px 1px, rgba(15, 15, 15, 0.1) 0px 2px 4px;
    `;

    // Add loading handler
    img.onload = () => {
      console.log('Image loaded successfully');
    };

    img.onerror = () => {
      showNotification('Failed to load generated image', 'error');
    };

    // Assemble the structure
    imageWrapper.appendChild(img);
    imageBlock.appendChild(imageWrapper);

    // Insert after the selected block
    if (afterBlock && afterBlock.parentNode) {
      afterBlock.parentNode.insertBefore(imageBlock, afterBlock.nextSibling);
    } else {
      // Fallback: append to the page content
      const pageContent = document.querySelector('[data-block-id]')?.parentNode;
      if (pageContent) {
        pageContent.appendChild(imageBlock);
      }
    }

    console.log('Image inserted into Notion page');
  } catch (error) {
    console.error('Error inserting image:', error);
    showNotification('Failed to insert image into page', 'error');
  }
}

// Generate a UUID for the new block
function generateUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Show prompt selection modal
async function showPromptModal(selectedText) {
  return new Promise(async (resolve) => {
    // Get presets from storage
    const { presets = [] } = await chrome.storage.sync.get(['presets']);

    // Create modal overlay
    const overlay = document.createElement('div');
    overlay.id = 'nanobanana-prompt-modal-overlay';
    overlay.className = 'nanobanana-modal-overlay';

    // Create modal
    const modal = document.createElement('div');
    modal.className = 'nanobanana-modal';
    modal.innerHTML = `
      <div class="nanobanana-modal-header">
        <h3>プロンプトを選択 (Select Prompt)</h3>
        <button class="nanobanana-modal-close" title="Close">✕</button>
      </div>
      <div class="nanobanana-modal-body">
        <div class="nanobanana-prompt-option">
          <input type="radio" id="prompt-selected-text" name="prompt-type" value="selected" checked>
          <label for="prompt-selected-text">
            <strong>選択したテキストを使用 (Use selected text)</strong>
            <div class="prompt-preview">${escapeHtml(selectedText)}</div>
          </label>
        </div>

        ${presets.length > 0 ? `
          <div class="nanobanana-prompt-option">
            <input type="radio" id="prompt-preset" name="prompt-type" value="preset">
            <label for="prompt-preset">
              <strong>プリセットを使用 (Use preset)</strong>
            </label>
            <select id="preset-selector" class="nanobanana-select" disabled>
              ${presets.map((p, i) => `<option value="${i}">${escapeHtml(p.name)}</option>`).join('')}
            </select>
          </div>
        ` : ''}

        <div class="nanobanana-prompt-option">
          <input type="radio" id="prompt-custom" name="prompt-type" value="custom">
          <label for="prompt-custom">
            <strong>カスタムプロンプト (Custom prompt)</strong>
          </label>
          <textarea id="custom-prompt-input" class="nanobanana-textarea" rows="4" placeholder="Enter your custom prompt..." disabled></textarea>
        </div>
      </div>
      <div class="nanobanana-modal-footer">
        <button class="nanobanana-btn nanobanana-btn-secondary" id="modal-cancel">キャンセル (Cancel)</button>
        <button class="nanobanana-btn nanobanana-btn-primary" id="modal-generate">生成 (Generate)</button>
      </div>
    `;

    overlay.appendChild(modal);
    document.body.appendChild(overlay);

    // Setup event listeners
    const closeBtn = modal.querySelector('.nanobanana-modal-close');
    const cancelBtn = modal.querySelector('#modal-cancel');
    const generateBtn = modal.querySelector('#modal-generate');
    const radioButtons = modal.querySelectorAll('input[name="prompt-type"]');
    const presetSelector = modal.querySelector('#preset-selector');
    const customInput = modal.querySelector('#custom-prompt-input');

    // Enable/disable inputs based on radio selection
    radioButtons.forEach(radio => {
      radio.addEventListener('change', () => {
        if (presetSelector) {
          presetSelector.disabled = radio.value !== 'preset';
        }
        if (customInput) {
          customInput.disabled = radio.value !== 'custom';
        }
      });
    });

    // Close modal
    const closeModal = () => {
      overlay.remove();
      resolve(null);
    };

    closeBtn.addEventListener('click', closeModal);
    cancelBtn.addEventListener('click', closeModal);
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) closeModal();
    });

    // Generate button
    generateBtn.addEventListener('click', () => {
      const selectedType = modal.querySelector('input[name="prompt-type"]:checked').value;
      let finalPrompt = '';

      if (selectedType === 'selected') {
        finalPrompt = selectedText;
      } else if (selectedType === 'preset' && presetSelector) {
        const presetIndex = parseInt(presetSelector.value);
        const preset = presets[presetIndex];
        // Replace {text} with selected text
        finalPrompt = preset.prompt.replace(/\{text\}/g, selectedText);
      } else if (selectedType === 'custom' && customInput) {
        finalPrompt = customInput.value.trim();
        if (!finalPrompt) {
          showNotification('カスタムプロンプトを入力してください (Please enter custom prompt)', 'error');
          return;
        }
      }

      overlay.remove();
      resolve(finalPrompt);
    });

    // Focus on modal
    setTimeout(() => overlay.classList.add('show'), 10);
  });
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

// Show notification
function showNotification(message, type = 'info') {
  const notification = document.createElement('div');
  notification.className = `nanobanana-notification nanobanana-notification-${type}`;
  notification.textContent = message;
  document.body.appendChild(notification);

  setTimeout(() => {
    notification.classList.add('show');
  }, 10);

  setTimeout(() => {
    notification.classList.remove('show');
    setTimeout(() => notification.remove(), 300);
  }, 3000);
}

// Content script is now event-driven (no initialization needed)
